version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    command: npm run dev

  redis:
    image: redis:7
    ports:
      - "6379:6379"